export const currencies = [
  { code: "USD", name: "USD - United States Dollar" },
  { code: "EUR", name: "EUR - Euro" },
  { code: "JPY", name: "JPY - Japanese Yen" },
  { code: "GBP", name: "GBP - British Pound" },
  { code: "CHF", name: "CHF - Swiss Franc" },
  { code: "AUD", name: "AUD - Australian Dollar" },
  { code: "CAD", name: "CAD - Canadian Dollar" },
  { code: "SEK", name: "SEK - Swedish Krona" },
  { code: "NZD", name: "NZD - New Zealand Dollar" },
  { code: "INR", name: "INR - Indian Rupee" },
  { code: "IDR", name: "IDR - Indonesian Rupiah" },
  { code: "BRL", name: "BRL - Brazilian Real" },
  { code: "MXN", name: "MXN - Mexican Peso" },
  { code: "KRW", name: "KRW - South Korean Won" },
  { code: "SGD", name: "SGD - Singapore Dollar" },
  { code: "HKD", name: "HKD - Hong Kong Dollar" },
  { code: "TRY", name: "TRY - Turkish Lira" },
  { code: "ZAR", name: "ZAR - South African Rand" },
  { code: "ARS", name: "ARS - Argentine Peso" },
  { code: "XOF", name: "XOF - West African CFA Franc" },
  { code: "KWD", name: "KWD - Kuwaiti Dinar" },
  { code: "BHD", name: "BHD - Bahraini Dinar" },
  { code: "JOD", name: "JOD - Jordanian Dinar" },
  { code: "AED", name: "AED - United Arab Emirates Dirham" },
  { code: "KHR", name: "KHR - Cambodian Riel" },
  { code: "LAK", name: "LAK - Lao Kip" },
  { code: "VND", name: "VND - Vietnamese Dong" },
  { code: "CZK", name: "CZK - Czech Koruna" },
  { code: "BDT", name: "BDT - Bangladeshi Taka" },
  { code: "CLP", name: "CLP - Chilean Peso" }
];
